ds.default:
  url: "jdbc:sqlserver://CATELAN\\SQLEXPRESS;databaseName=TF_BANCO;sendStringParametersAsUnicode=false;encrypt=false;"

arch:
  security.jwt.algorithm: RS256
micronaut:
  server:
    port: 8080
management:
  port: "9090"

