openapi: 3.0.1

info:
  title: API Banco
  description: API do banco
  version: 0.0.1
  contact:
    name: "Autbank"
    url: "http://www.autbank.com.br/"
    email: "contato@autbank.com.br"

servers:
  - url: /

paths:
  /secured/envios-exterior:
    post:
      summary: Realiza cadastro de operação de envio ao exterior
      description: Realiza cadastro de operação de envio ao exterior
      operationId: envioExterior
      security:
        - microservice_auth:
            - TF_001_ENVIOSEXTERIOR:POST
      requestBody:
        description: Dados necessários para envio ao exterior
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformacoesEnvioExterior'

      responses:
        200:
          description: Informações de Envio Exterior incluído com sucesso

  /transferencias:
    post:
      summary: Realiza a transferencia
      description: Realiza a transferencia
      operationId: realizaTransferencia
      requestBody:
        description: Dados necessários para transferencia
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformacoesTransferencia'
      responses:
        200:
          description: Informações de transferências incluídas com sucesso

components:
  schemas:
    InformacoesTransferencia:
      type: object
      properties:
        idRemessa:
          type: integer
        valor:
          type: number
        titularDeb:
          type: string
        nroContaDeb:
          type: string
        titularCred:
          type: string
        nroContaCred:
          type: string
    InformacoesEnvioExterior:
      type: object
      properties:
        idRemessa:
          type: integer
        valor:
          type: number
        status:
          type: string

  securitySchemes:
    microservice_auth:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "/proxy/oauth/token"
          scopes:
            TF_001_ENVIOSEXTERIOR:POST: "Permissão para inserir envio exterior"
            TF_001_ENVIOSEXTERIOR:PATCH: "Permissão para editar envio exterior"
            TF_002_SENDMONEY:POST: "Permissão para enviar dinheiro"